services:
 grafana:
   image: 'grafana/grafana'
   ports:
    - 3000:3000
   user: "${UID}:${GID}"
   volumes:
    - ./grafana/var:/var/lib/grafana

 prometheus:
   image: 'bitnami/prometheus'
   ports:
    - 9090:9090
   user: "${UID}:${GID}"
   volumes:
    - ./prometheus/etc/prometheus.yml:/etc/prometheus/prometheus.yml
    - ./prometheus/data:/prometheus
   command:
    - "--config.file=/etc/prometheus/prometheus.yml"
    - "--storage.tsdb.path=/prometheus"
 node_exporter:
  image: 'prom/node-exporter'
  ports:
   - 9100:9100
  volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
  command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
